server:
  port: 8082
  servlet:
    # Context Path must be specified.
    # reason : the session tracking is cookie based and each session cookie must have a unique path
    context-path: /auth

spring:
  jpa:
    # Driver Class = org.h2.Driver
    # JDBC URL = jdbc:h2:mem:testdb
    database-platform: H2
    show-sql: TRUE
    hibernate:
      ddl-auto: 'create-drop'

  h2:
    console:
      enabled: TRUE
      path: /h2-console

# Custom Property
security:
  oauth2:
    resource:
      email-duplicated-check-uri: http://localhost:8081/resource/user/email/checkDuplicated
      email-add-uri: http://localhost:8081/resource/user/email/add